#生产环境
spring:
  datasource:
    #连接数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 200309
  servlet:
  # 配置servlet的multipart设置，用于文件上传
    multipart:
      # 启用multipart文件上传功能
      enabled: true
      # 设置单个文件的最大大小为10MBcdm
      max-file-size: 10MB
      # 设置整个HTTP请求的最大大小为10MB，适应单文件或多文件上传
      max-request-size: 10MB
  data:
    ##Redis非关系形数据库配置
    redis:
      port: 6379
      host: 127.0.0.1
server:
  #配置项目运行的端口
  port: 8080 #设置端口
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名自动转换
# 七牛云配置
qiniu:
  access-key: z0lp5utyQDwWhh4mgaYUOSiDQXTFltEe1MHE1N0q
  secret-key: Un5jzbRYYmeCgC01vrpko4NH4O3ZzHPxSNElOxkb
  bucket-name: uploadlwz
  domain: http://sncodwj9m.hn-bkt.clouddn.com #https://portal.qiniu.com/
