#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 200309

server:
  port: 8081 #设置端口
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名自动转换
